# Generated by Django 3.0.6 on 2020-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_description', models.CharField(max_length=255)),
                ('stock_price', models.CharField(max_length=6)),
            ],
        ),
    ]
