# Generated by Django 3.0.6 on 2020-06-01 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('stockmanager', '0002_auto_20200601_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signup.Signup'),
            preserve_default=False,
        ),
    ]
